# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # 在推送到 main 分支时运行
  push:
    branches: ["main"]

  # 允许从 Actions 标签手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 单个部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Create root directory
        run: |
          mkdir -p public
          cp -r * public/ || true
          cp .nojekyll public/ || true
          echo "<!DOCTYPE html><meta http-equiv=\"refresh\" content=\"0; url=index.html\">" > public/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 